//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchSetup.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MatchSetup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Settings&gt;
        ///    &lt;BoardSize&gt;11&lt;/BoardSize&gt;
        ///    &lt;KingPosition&gt;
        ///        &lt;Position row=&quot;5&quot; column=&quot;5&quot;/&gt;
        ///    &lt;/KingPosition&gt;
        ///    &lt;ExitsPositions&gt;
        ///        &lt;Position row=&quot;0&quot; column=&quot;0&quot;/&gt;
        ///        &lt;Position row=&quot;0&quot; column=&quot;10&quot;/&gt;
        ///        &lt;Position row=&quot;10&quot; column=&quot;0&quot;/&gt;
        ///        &lt;Position row=&quot;10&quot; column=&quot;10&quot;/&gt;
        ///    &lt;/ExitsPositions&gt;
        ///    &lt;AttackerBasicPiecesPositions&gt;
        ///        &lt;Position row=&quot;0&quot; column=&quot;3&quot;/&gt;
        ///        &lt;Position row=&quot;0&quot; column=&quot;4&quot;/&gt;
        ///        &lt;Position row=&quot;0&quot; column=&quot;5&quot;/&gt; [stringa troncata]&quot;;.
        /// </summary>
        public static string ClassicModeSettings {
            get {
                return ResourceManager.GetString("ClassicModeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Settings&gt;
        ///
        ///    &lt;BoardSize&gt;11&lt;/BoardSize&gt;
        ///
        ///    &lt;KingPosition&gt;
        ///        &lt;Position row=&quot;5&quot; column=&quot;5&quot;/&gt;
        ///    &lt;/KingPosition&gt;
        ///
        ///    &lt;ExitsPositions&gt;
        ///        &lt;Position row=&quot;0&quot; column=&quot;0&quot;/&gt;
        ///        &lt;Position row=&quot;0&quot; column=&quot;10&quot;/&gt;
        ///        &lt;Position row=&quot;10&quot; column=&quot;0&quot;/&gt;
        ///        &lt;Position row=&quot;10&quot; column=&quot;10&quot;/&gt;
        ///    &lt;/ExitsPositions&gt;
        ///
        ///    &lt;SlidersPositions&gt;
        ///        &lt;Position row=&quot;2&quot; column=&quot;2&quot;/&gt;
        ///        &lt;Position row=&quot;2&quot; column=&quot;8&quot;/&gt;
        ///        &lt;Position row=&quot;8&quot; column=&quot;2&quot;/&gt;
        ///        [stringa troncata]&quot;;.
        /// </summary>
        public static string VariantModeSettings {
            get {
                return ResourceManager.GetString("VariantModeSettings", resourceCulture);
            }
        }
    }
}
